apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends-deployment
  namespace: { { .Values.namespace.name } }
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
        - name: techtrends
          image: techtrends:latest
          ports:
            - containerPort: { { .Values.service.port } }
          resources:
            requests:
              memory: { { .Values.resources.requests.memory } }
              cpu: { { .Values.resources.requests.cpu } }
            limits:
              memory: { { .Values.resources.limits.memory } }
              cpu: { { .Values.resources.limits.cpu } }
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3111
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3111
            initialDelaySeconds: 10
            periodSeconds: 20
